package main

import (
	"net/http"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestAnalyzePackageAndRender(t *testing.T) {
	packageName, handlers, err := analyzePackage(options{dir: "testdata/sample", framework: "gin"})
	require.NoError(t, err)
	require.Len(t, handlers, 5)
	assert.Equal(t, "sample", packageName)
	assert.Equal(t, "Create", handlers[0].name)
	assert.Contains(t, handlers[0].request.Properties, "amount")
	assert.Contains(t, handlers[0].request.Required, "amount")
	assert.Contains(t, handlers[0].response.Properties, "id")
	assert.Equal(t, http.StatusCreated, handlers[0].responseStatus)

	deleted := findGeneratedHandler(t, handlers, "Delete")
	assert.Equal(t, http.StatusNoContent, deleted.responseStatus)
	assert.Empty(t, deleted.response)

	generated, err := renderGeneratedFile(packageName, handlers)
	require.NoError(t, err)
	assert.True(t, strings.HasPrefix(string(generated), "// Code generated by openapi-gen. DO NOT EDIT."))
	assert.Contains(t, string(generated), `RegisterGeneratedHandlerSchema("github.com/thiagozs/go-openapi-gen/cmd/openapi-gen/testdata/sample.Handler.Create"`)
}

func TestAnalyzeHertzPackage(t *testing.T) {
	packageName, handlers, err := analyzePackage(options{
		dir:       "testdata/hertzsample",
		framework: "hertz",
	})
	require.NoError(t, err)
	require.Len(t, handlers, 4)
	assert.Equal(t, "hertzsample", packageName)
	assert.Equal(t, "Create", handlers[0].name)
	assert.Contains(t, handlers[0].request.Properties, "amount")
	assert.Contains(t, handlers[0].request.Required, "amount")
	assert.Contains(t, handlers[0].response.Properties, "id")
}

func TestAnalyzeCollectionResponses(t *testing.T) {
	for _, test := range []struct {
		name      string
		dir       string
		framework string
	}{
		{name: "gin", dir: "testdata/sample", framework: "gin"},
		{name: "hertz", dir: "testdata/hertzsample", framework: "hertz"},
	} {
		t.Run(test.name, func(t *testing.T) {
			_, handlers, err := analyzePackage(options{dir: test.dir, framework: test.framework})
			require.NoError(t, err)

			list := findGeneratedHandler(t, handlers, "List")
			require.Equal(t, "array", list.response.Type)
			require.NotNil(t, list.response.Items)
			assert.Contains(t, list.response.Items.Properties, "id")

			index := findGeneratedHandler(t, handlers, "Index")
			assert.Equal(t, "object", index.response.Type)
			require.NotNil(t, index.response.AdditionalProperties)
			assert.Contains(t, index.response.AdditionalProperties.Properties, "id")

			envelope := findGeneratedHandler(t, handlers, "ListEnvelope")
			data, exists := envelope.response.Properties["data"]
			require.True(t, exists)
			require.Equal(t, "array", data.Type)
			require.NotNil(t, data.Items)
			assert.Contains(t, data.Items.Properties, "id")
		})
	}
}

func findGeneratedHandler(t *testing.T, handlers []generatedHandler, name string) generatedHandler {
	t.Helper()
	for _, handler := range handlers {
		if handler.name == name {
			return handler
		}
	}
	t.Fatalf("handler %s not found", name)
	return generatedHandler{}
}
