package main

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestAnalyzePackageAndRender(t *testing.T) {
	packageName, handlers, err := analyzePackage(options{dir: "testdata/sample", framework: "gin"})
	require.NoError(t, err)
	require.Len(t, handlers, 1)
	assert.Equal(t, "sample", packageName)
	assert.Equal(t, "Create", handlers[0].name)
	assert.Contains(t, handlers[0].request.Properties, "amount")
	assert.Contains(t, handlers[0].request.Required, "amount")
	assert.Contains(t, handlers[0].response.Properties, "id")

	generated, err := renderGeneratedFile(packageName, handlers)
	require.NoError(t, err)
	assert.True(t, strings.HasPrefix(string(generated), "// Code generated by openapi-gen. DO NOT EDIT."))
	assert.Contains(t, string(generated), `RegisterGeneratedHandlerSchema("github.com/thiagozs/go-openapi-gen/cmd/openapi-gen/testdata/sample.Handler.Create"`)
}

func TestAnalyzeHertzPackage(t *testing.T) {
	packageName, handlers, err := analyzePackage(options{
		dir:       "testdata/hertzsample",
		framework: "hertz",
	})
	require.NoError(t, err)
	require.Len(t, handlers, 1)
	assert.Equal(t, "hertzsample", packageName)
	assert.Equal(t, "Create", handlers[0].name)
	assert.Contains(t, handlers[0].request.Properties, "amount")
	assert.Contains(t, handlers[0].request.Required, "amount")
	assert.Contains(t, handlers[0].response.Properties, "id")
}
